#!/usr/bin/env python
from __future__ import absolute_import
from __future__ import print_function
from .customPost import custom_post
import yaml
import os

#cwd = os.getenv('PWD')
#os.getcwd()
#os.system('ls')
settings_in = None
priors_in = None
advanced_settings_in = None
if os.path.exists('./settings.yaml'):
    f = open('./settings.yaml','r')
    settings_in = yaml.load(f)
    f.close()
if os.path.exists('./advanced_settings.yaml'):
    f = open('./advanced_settings.yaml','r')
    advanced_settings_in = yaml.load(f)
    f.close()
if os.path.exists('./priors.py'):
    from priors import ExoSOFTpriors as priors_in

custom_post(settings_in,advanced_settings_in, priors_in)