#!/usr/bin/env python
from __future__ import absolute_import
from __future__ import print_function
from ExoSOFT import custom_post
#import sys
import os

#cwd = os.getenv('PWD')
#os.getcwd()
#os.system('ls')
settings_in = None
priors_in = None
if os.path.exists('./settings.py'):
    #print("Yup!  settings.py is here")
    from settings import settings as settings_in
    #print(repr(settings))
if os.path.exists('./priors.py'):
    #print("Yup!  priors.py is here")
    from priors import ExoSOFTpriors as priors_in
    #print(repr(ExoSOFTpriors))

custom_post(settings_in, priors_in)