# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_hello', [dirname(__file__)])
        except ImportError:
            import _hello
            return _hello
        if fp is not None:
            try:
                _mod = imp.load_module('_hello', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _hello = swig_import_helper()
    del swig_import_helper
else:
    import _hello
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_hello.HELLO_H_swigconstant(_hello)
HELLO_H = _hello.HELLO_H

def cadd(x, y):
    return _hello.cadd(x, y)
cadd = _hello.cadd

def selection(flag):
    return _hello.selection(flag)
selection = _hello.selection

def fact(n):
    return _hello.fact(n)
fact = _hello.fact

def csin(i):
    return _hello.csin(i)
csin = _hello.csin

def speak(str):
    return _hello.speak(str)
speak = _hello.speak

def sum_scalar(x, y):
    return _hello.sum_scalar(x, y)
sum_scalar = _hello.sum_scalar

def sum_1d(nx, ny):
    return _hello.sum_1d(nx, ny)
sum_1d = _hello.sum_1d

def sum2d(x):
    return _hello.sum2d(x)
sum2d = _hello.sum2d

def sumfunc(nx, ny, op):
    return _hello.sumfunc(nx, ny, op)
sumfunc = _hello.sumfunc

def sum2d_double(x, nx, ny):
    return _hello.sum2d_double(x, nx, ny)
sum2d_double = _hello.sum2d_double
# This file is compatible with both classic and new-style classes.


