# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_orbCalc2', [dirname(__file__)])
        except ImportError:
            import _orbCalc2
            return _orbCalc2
        if fp is not None:
            try:
                _mod = imp.load_module('_orbCalc2', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _orbCalc2 = swig_import_helper()
    del swig_import_helper
else:
    import _orbCalc2
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_orbCalc2.ORBCALC2_H_swigconstant(_orbCalc2)
ORBCALC2_H = _orbCalc2.ORBCALC2_H
class OrbCalcObj(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OrbCalcObj, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OrbCalcObj, name)
    __repr__ = _swig_repr
    __swig_setmethods__["testDouble"] = _orbCalc2.OrbCalcObj_testDouble_set
    __swig_getmethods__["testDouble"] = _orbCalc2.OrbCalcObj_testDouble_get
    if _newclass:
        testDouble = _swig_property(_orbCalc2.OrbCalcObj_testDouble_get, _orbCalc2.OrbCalcObj_testDouble_set)
    __swig_setmethods__["dataAry"] = _orbCalc2.OrbCalcObj_dataAry_set
    __swig_getmethods__["dataAry"] = _orbCalc2.OrbCalcObj_dataAry_get
    if _newclass:
        dataAry = _swig_property(_orbCalc2.OrbCalcObj_dataAry_get, _orbCalc2.OrbCalcObj_dataAry_set)
    __swig_setmethods__["dataAry_x"] = _orbCalc2.OrbCalcObj_dataAry_x_set
    __swig_getmethods__["dataAry_x"] = _orbCalc2.OrbCalcObj_dataAry_x_get
    if _newclass:
        dataAry_x = _swig_property(_orbCalc2.OrbCalcObj_dataAry_x_get, _orbCalc2.OrbCalcObj_dataAry_x_set)
    __swig_setmethods__["dataAry_y"] = _orbCalc2.OrbCalcObj_dataAry_y_set
    __swig_getmethods__["dataAry_y"] = _orbCalc2.OrbCalcObj_dataAry_y_get
    if _newclass:
        dataAry_y = _swig_property(_orbCalc2.OrbCalcObj_dataAry_y_get, _orbCalc2.OrbCalcObj_dataAry_y_set)

    def loadData(self, xx):
        return _orbCalc2.OrbCalcObj_loadData(self, xx)

    def calculator(self, yy):
        return _orbCalc2.OrbCalcObj_calculator(self, yy)

    def __init__(self):
        this = _orbCalc2.new_OrbCalcObj()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _orbCalc2.delete_OrbCalcObj
    __del__ = lambda self: None
OrbCalcObj_swigregister = _orbCalc2.OrbCalcObj_swigregister
OrbCalcObj_swigregister(OrbCalcObj)


def testFunc(t):
    return _orbCalc2.testFunc(t)
testFunc = _orbCalc2.testFunc
# This file is compatible with both classic and new-style classes.


